name: .NET

on:
  pull_request:
    types: [ reopened, open, closed, synchronize]

jobs:
  build:
    if: |
      (github.event.pull_request.state == 'open' && github.event.pull_request.merged == false) 
      || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Ciphers.sln
    - name: Build
      run: dotnet build Ciphers.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal Ciphers.sln
